class CreateProperties < ActiveRecord::Migration[5.1]
  def change
    create_table :properties do |t|
      t.string :property_type1
      t.string :property_type2
      t.string :transaction_type
      t.date :mediation_date
      t.integer :condition
      t.text :supplementary_explanation
      t.integer :postal_code
      t.string :prefecture
      t.string :city
      t.text :street
      t.boolean :show_street
      t.text :apartment_name
      t.string :roomnumber
      t.string :buildingnumber
      t.boolean :show_roomnumber
      t.string :measurement
      t.string :land_area
      t.string :building_area1
      t.string :building_area2
      t.string :occupied_area
      t.string :balcony_area
      t.string :terrace_area
      t.string :privategarden_area
      t.string :driveway_burden
      t.string :driveway_area
      t.string :driveway_part1
      t.string :driveway_part2
      t.string :setback_class
      t.string :setback_distance
      t.string :setback_area
      t.string :alleyground_class
      t.string :alleyground_area
      t.string :firstfloor_area
      t.string :secondfloor_area
      t.string :thirdfloor_area
      t.text :otherfloor_area
      t.string :development_area1
      t.string :total_area
      t.integer :subdivision
      t.date :construction_date
      t.string :coownership_area
      t.string :coownership
      t.string :development_area2
      t.string :building_area3
      t.string :totalfloor_area
      t.string :route_name1
      t.text :station_name1
      t.string :station_walkm1
      t.string :station_walkd1
      t.string :station_car1
      t.string :station_bus1
      t.string :busstop_walkm1
      t.string :busstop_walkd1
      t.text :busroute_name1
      t.text :busstop_name1
      t.string :route_name2
      t.text :station_name2
      t.string :station_walkm2
      t.string :station_walkd2
      t.string :station_car2
      t.string :station_bus2
      t.string :busstop_walkm2
      t.string :busstop_walkd2
      t.text :busroute_name2
      t.text :busstop_name2
      t.string :route_name3
      t.text :station_name3
      t.string :station_walkm3
      t.string :station_walkd3
      t.string :station_car3
      t.string :station_bus3
      t.string :busstop_walkm3
      t.string :busstop_walkd3
      t.text :busroute_name3
      t.text :busstop_name3
      t.text :other_transportation
      t.string :floor_plan
      t.integer :room
      t.boolean :corner_room
      t.integer :room_level1
      t.string :room_type1
      t.string :room_size1
      t.integer :room_level2
      t.string :room_type2
      t.string :room_size2
      t.integer :room_level3
      t.string :room_type3
      t.string :room_size3
      t.integer :room_level4
      t.string :room_type4
      t.string :room_size4
      t.integer :room_level5
      t.string :room_type5
      t.string :room_size5
      t.integer :room_level6
      t.string :room_type6
      t.string :room_size6
      t.integer :room_level7
      t.string :room_type7
      t.string :room_size7
      t.integer :room_level8
      t.string :room_type8
      t.string :room_size8
      t.integer :room_level9
      t.string :room_type9
      t.string :room_size9
      t.text :other_room
      t.integer :price
      t.integer :consumption_tax
      t.string :situation
      t.date :situation_date
      t.string :transfer
      t.string :transfer_date
      t.date :move_date
      t.string :remuneration
      t.integer :fee_part
      t.integer :fee_amount
      t.string :town_plan
      t.string :register_landcategory
      t.string :situation_landcategory
      t.string :zoning1
      t.string :zoning2
      t.string :optimum_site
      t.string :zoning_district
      t.integer :buildingcoverage_ratio
      t.integer :floorarea_ratio
      t.string :floorarea_restriction
      t.text :law_restriction
      t.boolean :rebuilding
      t.string :nationalland_law
      t.string :buildingcertification
      t.string :buildingcertification_number
      t.string :land_title
      t.string :terrain
      t.string :architectural_condition
      t.string :connecting_road
      t.string :paved_road
      t.string :road_class1
      t.string :contact_distance1
      t.string :designation_road1
      t.string :road_direction1
      t.string :road_width1
      t.string :road_class2
      t.string :contact_distance2
      t.string :designation_road2
      t.string :road_direction2
      t.string :road_width2
      t.string :road_class3
      t.string :contact_distance3
      t.string :designation_road3
      t.string :road_direction3
      t.string :road_width3
      t.string :road_class4
      t.string :contact_distance4
      t.string :designation_road4
      t.string :road_direction4
      t.string :road_width4
      t.string :homeowner_association

      t.timestamps
    end
  end
end
